### ISSUE TITLE
SignalR Aurelia TypeScript

### ISSUE THREAD

**Issue by radu-matei** [TravcoLtd/aurelia-signalr#1]
Is it possible to use this with TypeSrcipt?

Thanks!

**Comment by victorarbuesmallada** [comment]
Hi Radu,

I haven't done anything to make it work with typescript nor I'm familiar with typescript to tell you the truth. Might do something about it if I got the time but if you are willing to fork it and do it yourself, please be my guest :)

**Comment by radu-matei** [comment]
Ok. Could you please provide an implementation of aurelia and signalR? Thanks!

**Comment by radu-matei** [comment]
Closing this as there are new versions for both SignalR and Aurelia.

Thanks,
Radu M
